name: ci

on: push

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - dockerfile: poc-password-generator/Dockerfile
            context: poc-password-generator/
            image: mailinenguyen/poc-password-generator
          - dockerfile: poc-password-mail-sender/Dockerfile
            context: poc-password-mail-sender/
            image: mailinenguyen/poc-password-mail-sender
          - dockerfile: poc-protools/Dockerfile
            context: poc-protools/
            image: mailinenguyen/poc-protools
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Docker meta ${{ matrix.image }}
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ matrix.image }} # list of Docker images to use as base name for tags
      - name: Build and push ${{ matrix.image }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.docker_meta.outputs.tags }}
            ${{ github.ref == 'refs/heads/master' && format('{0}:latest', matrix.image) || '' }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
